name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.paths, 'backend'))
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and test backend
        run: mvn -B verify
        working-directory: ./backend

#  frontend:
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.paths, 'frontend'))
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '14'
#      - name: Install dependencies
#        run: npm ci
#        working-directory: ./frontend
#      - name: Build and test frontend
#        run: npm run build && npm test
#        working-directory: ./frontend